name: custom_lint_example
version: 1.0.0

environment:
  sdk: '>=2.17.3 <3.0.0'

dependencies:
  riverpod: ^2.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  analyzer:
  analyzer_plugin:
  custom_lint:
  custom_lint_example_lint:
    path: ./example_lint